#Service-Name
service: cj-enm-poc-gen-ai

#Python Version 3.12
runtime: python312

#Larger Instance Class to Prevent Large Request Error
instance_class: F4_1G

#Environment Variables
includes:
  - env_variables.yaml

#Static files directory
handlers:
  - url: /static/demo
    static_dir: static/demo
  - url: /static/admin
    static_dir: static/admin